dubbo:
  application:
    name: dubbo-provider-demo
    qosEnable: true
    qosPort: 22222
    qosAcceptForeignIp: false
  protocol:
    port: 20880
    name: dubbo
#    serialization: kryo
  registry:
    address: nacos://192.168.50.10:8848
    simplified: false
    register: false

spring:
  profiles:
    include: nacos
    active: public

server:
  port: 8081




  
  