dubbo:
  application:
    name: dubbo-consumer-demo
    qosEnable: true
    qosPort: 33333
    qosAcceptForeignIp: false
  protocol:
    port: 20880
    name: dubbo
  #   serialization: kryo
  registry:
    address: nacos://192.168.50.10:8848
    simplified: false


spring:
  profiles:
    include: nacos

server:
  port: 8082


